import { CarlistingSeed } from "../../src/helpers/types";

export const carlisting: CarlistingSeed[] = [
  {
    mileage: 17304,
    description: "2.0TSI R-Line 4Motion DSG",
    price: 41900,
    makeId: 1,
    modelId: 1,
    gearboxId: 2,
    driveId: 1,
    fuelId: 2,
    is_online: true,
  },
  {
    mileage: 68939,
    description: "1.2 TSI Trendline",
    price: 11900,
    makeId: 1,
    modelId: 2,
    gearboxId: 2,
    driveId: 2,
    fuelId: 1,
    is_online: true,
  },
  {
    mileage: 74658,
    description: "1.6 TSI Trendline",
    price: 13900,
    makeId: 1,
    modelId: 2,
    gearboxId: 2,
    driveId: 2,
    fuelId: 3,
    is_online: true,
  },
  {
    mileage: 9359,
    description: "1.5 TSI DSG",
    price: 32400,
    makeId: 6,
    modelId: 3,
    gearboxId: 1,
    driveId: 2,
    fuelId: 2,
    is_online: true,
  },
  {
    mileage: 18170,
    description: "2.0 TDI DSG Style",
    price: 27500,
    makeId: 2,
    modelId: 4,
    gearboxId: 1,
    driveId: 2,
    fuelId: 3,
    is_online: true,
  },
  {
    mileage: 58605,
    description: "1.0 MPI Monte Carlo",
    price: 13890,
    makeId: 2,
    modelId: 5,
    gearboxId: 2,
    driveId: 2,
    fuelId: 2,
    is_online: true,
  },
  {
    mileage: 22721,
    description: "2.0TSI VZ 4Drive DSG",
    price: 37600,
    makeId: 6,
    modelId: 3,
    gearboxId: 1,
    driveId: 1,
    fuelId: 2,
    is_online: true,
  },
  {
    mileage: 30755,
    description: "2.0 TDI Life DSG",
    price: 23900,
    makeId: 1,
    modelId: 2,
    gearboxId: 1,
    driveId: 3,
    fuelId: 3,
    is_online: true,
  },
];
